markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: true 

paginate: 8 
paginate_path: "page:num"

# presonal config
title: Mina's Papa Blog
description: copyright by malphi, powered by malphi
feed: http://www.malphi.net/atom.xml

author: malphi

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
