markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: true 

paginate: 8 
paginate_path: "page:num"

# presonal config
title: Hanlin_Li Blog
description: copyright by Hanlin_Li Blog, powered by Hanlin_Li Blog
feed: Hanlin_Li Blog

author: Hanlin

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
